import StyleDictionary from 'style-dictionary';
import { mkdirSync } from 'fs';

// ---- カスタムフォーマット: CSS変数 ----
StyleDictionary.registerFormat({
  name: 'kakka/css/variables',
  format: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .map(token => `  --kakka-${token.path.join('-')}: ${token.value};`)
      .join('\n');
    return `/* Auto-generated by Style Dictionary - DO NOT EDIT */\n:root {\n${vars}\n}\n`;
  },
});

// ---- カスタムフォーマット: TypeScript定数 ----
StyleDictionary.registerFormat({
  name: 'kakka/typescript/constants',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map(token => {
        const key = token.path
          .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
          .join('');
        const safeKey = /^\d/.test(key) ? `_${key}` : key;
        return `  '${safeKey}': ${JSON.stringify(token.value)},`;
      })
      .join('\n');
    return `// Auto-generated by Style Dictionary - DO NOT EDIT\nexport const tokens = {\n${entries}\n} as const;\n\nexport type TokenKey = keyof typeof tokens;\n`;
  },
});

// ---- カスタムフォーマット: TypeScript 型定義 ----
StyleDictionary.registerFormat({
  name: 'kakka/typescript/declarations',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map(token => {
        const key = token.path
          .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
          .join('');
        const safeKey = /^\d/.test(key) ? `_${key}` : key;
        return `  '${safeKey}': string;`;
      })
      .join('\n');
    return `// Auto-generated by Style Dictionary - DO NOT EDIT\nexport declare const tokens: {\n${entries}\n};\nexport type TokenKey = keyof typeof tokens;\n`;
  },
});

// ---- カスタムフォーマット: Android colors.xml ----
StyleDictionary.registerFormat({
  name: 'kakka/android/colors',
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(t => t.path[0] === 'color');
    const items = colorTokens.map(token => {
      const name = `kakka_${token.path.join('_')}`;
      const hex = String(token.value).replace('#', '');
      return `    <color name="${name}">#FF${hex.toUpperCase()}</color>`;
    }).join('\n');
    return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Auto-generated by Style Dictionary - DO NOT EDIT -->\n<resources>\n${items}\n</resources>\n`;
  },
});

// ---- カスタムフォーマット: Android dimens.xml ----
StyleDictionary.registerFormat({
  name: 'kakka/android/dimens',
  format: ({ dictionary }) => {
    const dimenTokens = dictionary.allTokens.filter(t =>
      ['spacing', 'borderRadius', 'font'].includes(t.path[0])
    );
    const items = dimenTokens.map(token => {
      const name = `kakka_${token.path.join('_')}`;
      const val = token.value;
      const isFont = token.path[0] === 'font' && token.path[1] === 'size';
      const unit = isFont ? 'sp' : 'dp';
      if (isNaN(Number(val))) return null;
      return `    <dimen name="${name}">${val}${unit}</dimen>`;
    }).filter(Boolean).join('\n');
    return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Auto-generated by Style Dictionary - DO NOT EDIT -->\n<resources>\n${items}\n</resources>\n`;
  },
});

// ---- カスタムフォーマット: Swift tokens ----
StyleDictionary.registerFormat({
  name: 'kakka/swift/tokens',
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      t => t.path[0] === 'color' && String(t.value).startsWith('#')
    );
    const spacingTokens = dictionary.allTokens.filter(t => t.path[0] === 'spacing');
    const radiusTokens = dictionary.allTokens.filter(t => t.path[0] === 'borderRadius');

    const toSwiftName = (path) =>
      path
        .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
        .join('')
        .replace(/[^a-zA-Z0-9_]/g, '_');

    const hexToSwift = (hex) => {
      const h = hex.replace('#', '');
      const r = (parseInt(h.slice(0, 2), 16) / 255).toFixed(4);
      const g = (parseInt(h.slice(2, 4), 16) / 255).toFixed(4);
      const b = (parseInt(h.slice(4, 6), 16) / 255).toFixed(4);
      return `Color(red: ${r}, green: ${g}, blue: ${b})`;
    };

    const colorLines = colorTokens.map(token => {
      const name = toSwiftName(token.path.slice(1));
      return `    public static let ${name} = ${hexToSwift(String(token.value))}`;
    }).join('\n');

    const spacingLines = spacingTokens.map(token => {
      const name = toSwiftName(['spacing', ...token.path.slice(1)]);
      return `    public static let ${name}: CGFloat = ${token.value}`;
    }).join('\n');

    const radiusLines = radiusTokens.map(token => {
      const name = toSwiftName(['radius', ...token.path.slice(1)]);
      return `    public static let ${name}: CGFloat = ${token.value === '9999' ? '999' : token.value}`;
    }).join('\n');

    return [
      '// Auto-generated by Style Dictionary - DO NOT EDIT',
      'import SwiftUI',
      '',
      '// MARK: - KakkaColors',
      'public enum KakkaColors {',
      colorLines,
      '}',
      '',
      '// MARK: - KakkaSpacing',
      'public enum KakkaSpacing {',
      spacingLines,
      '}',
      '',
      '// MARK: - KakkaRadius',
      'public enum KakkaRadius {',
      radiusLines,
      '}',
      '',
    ].join('\n');
  },
});

// ---- Style Dictionary 設定 ----
const sd = new StyleDictionary({
  source: ['src/tokens/**/*.json'],
  log: { verbosity: 'default' },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/css/',
      files: [{
        destination: 'variables.css',
        format: 'kakka/css/variables',
      }],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/js/',
      files: [
        {
          destination: 'index.js',
          format: 'kakka/typescript/constants',
        },
        {
          destination: 'index.d.ts',
          format: 'kakka/typescript/declarations',
        },
      ],
    },
    android: {
      transformGroup: 'android',
      buildPath: 'dist/android/',
      files: [
        {
          destination: 'colors.xml',
          format: 'kakka/android/colors',
        },
        {
          destination: 'dimens.xml',
          format: 'kakka/android/dimens',
        },
      ],
    },
    ios: {
      transformGroup: 'js',
      buildPath: 'dist/ios/',
      files: [{
        destination: 'KakkaTokens.swift',
        format: 'kakka/swift/tokens',
      }],
    },
  },
});

await sd.buildAllPlatforms();
console.log('\n✅ KAKKA tokens built successfully!');
